// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-wRcAyHjIDv6p8xkRwYRc2Tft8T69Cf4',
    appId: '1:912332702148:web:ddc8d13d449174492d2491',
    messagingSenderId: '912332702148',
    projectId: 'chat-app-50efc',
    authDomain: 'chat-app-50efc.firebaseapp.com',
    storageBucket: 'chat-app-50efc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXNJ_LN1bIgOFtzLEC70iEaUVYHKgL-3c',
    appId: '1:912332702148:android:3b9ff636d723a1072d2491',
    messagingSenderId: '912332702148',
    projectId: 'chat-app-50efc',
    storageBucket: 'chat-app-50efc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVeV8-uzbHvxYnn_5w8YKE5IV9ensJ5Ho',
    appId: '1:912332702148:ios:283474893c254bcf2d2491',
    messagingSenderId: '912332702148',
    projectId: 'chat-app-50efc',
    storageBucket: 'chat-app-50efc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVeV8-uzbHvxYnn_5w8YKE5IV9ensJ5Ho',
    appId: '1:912332702148:ios:dbd3f6bf3c2233972d2491',
    messagingSenderId: '912332702148',
    projectId: 'chat-app-50efc',
    storageBucket: 'chat-app-50efc.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
